### ISSUE TITLE
`eslint-plugin-unicorn` includes bug and needs to be upgraded

### ISSUE THREAD

**Issue by NozomuIkuta** [unjs/eslint-config#7]
### Environment

I encountered this bug with Node.js v18, but Node version doesn't matter in this time.

### Reproduction

Clone the unjs template repository and run `pnpm run lint` npm script.

### Describe the bug

when I tried to update unjs template repository, I encounted a bug in eslint-plugin-unicorn ([#2117](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2117)).

According to the issue, eslint-plugin-unicorn has to be upgraded to v46.0.1, which is major upgrade.

I will submit a PR although we have not yet resolve #6 because otherwise we can't use the template at the moment.

### Logs

```sh
pnpm run lint

> packageName@0.0.0 lint /Users/nozomuikuta/Repositories/unjs/template
> eslint --cache --ext .ts,.js,.mjs,.cjs . && prettier -c src test


Oops! Something went wrong! :(

ESLint: 8.40.0

TypeError: Cannot read properties of undefined (reading 'getAllComments')
Occurred while linting /Users/nozomuikuta/Repositories/unjs/template/src/index.ts:1
Rule: "unicorn/expiring-todo-comments"
    at Object.Program (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
    at Program (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint-plugin-unicorn@43.0.2_eslint@8.40.0/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:511:10)
    at /Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint-plugin-unicorn@43.0.2_eslint@8.40.0/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
    at ruleErrorHandler (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/linter.js:1049:28)
    at /Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/nozomuikuta/Repositories/unjs/template/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
 ELIFECYCLE  Command failed with exit code 2.
```

**Comment by NozomuIkuta** [comment]
I misspelled the magic word in the PR (`resovles #7`) 🙏
